### ISSUE TITLE
JungleControls exception (not working)

### ISSUE THREAD

**Issue by jdobrota** [robertvazan/junglecontrols#1]
Hello could you please check this exception ? We are using .NET Framework 4.7.2.
![image](https://user-images.githubusercontent.com/44607634/92570158-cc450600-f281-11ea-84b9-f84647cb6ec6.png)
![image](https://user-images.githubusercontent.com/44607634/92570394-26de6200-f282-11ea-87a0-057e1717a5ed.png)
![image](https://user-images.githubusercontent.com/44607634/92570532-50978900-f282-11ea-82d6-018cf327a22e.png)

**Exception:** 
System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message=Could not load file or assembly 'JungleControls, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at ALPR.UI.Views.VideoView.VideoControlView.InitializeComponent() in C:\Users\eny\Source\Repos\alprv2\ALPR.UI\Views\VideoView\VideoControlView.xaml:line 1
   at ALPR.UI.Views.VideoView.VideoControlView..ctor() in C:\Users\eny\Source\Repos\alprv2\ALPR.UI\Views\VideoView\VideoControlView.xaml.cs:line 29

Inner Exception 1:
FileNotFoundException: Could not load file or assembly 'JungleControls, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

**Comment by robertvazan** [comment]
Could you try a little experiment? Remove JungleControls references from XAML and try to use it directly from code. What exception will you get then? Can you say how you added the dependency and what development tool are you using for it? Perhaps post relevant nuget config file listing the package?

**Comment by robertvazan** [comment]
This library is no longer maintained. Feed free to adopt it if you find it useful.
